-- 01 TABLAS INDIVIDUALES QUE SE OCUPAN EN VARIAS TABLAS
CREATE TABLE CESTADOOS(
	EDO_PK_ID			INT PRIMARY KEY IDENTITY(1,1),
	EDO_DS_DESCRIPCION	VARCHAr(50),
	EDO_FE_UMOD			DATETIME,
	ACC_DS_USR			VARCHAR(10)
)
GO

CREATE TABLE CROLES(
	ROL_PK_ID			INT PRIMARY KEY IDENTITY(1,1),
	ROL_DS_DESCRIPCION	VARCHAR(50),
	EDO_PK_ID			INT,
	ROL_FE_UMOD			DATETIME,
	ACC_DS_USR			VARCHAR(10)
)
GO

CREATE TABLE CMENUS(
	MEN_PK_ID		INT PRIMARY KEY IDENTITY(1,1),
	MEN_NO_NIVEL	INT,
	MEN_ID_PADRE	INT,
	MEN_DS_MENU		VARCHAR(50),
	MEN_DS_ICONO    VARCHAR(50),
	MEN_DS_RUTA		VARCHAR(150),
	EDO_PK_ID		INT,
	MEN_FE_UMOD		DATETIME,
	ACC_DS_USR		VARCHAR(10)
)
GO

CREATE TABLE CPERFILES(
	PER_PK_ID		INT PRIMARY KEY IDENTITY(1,1),
	PER_DS_PERFIL	VARCHAR(50),
	EDO_PK_ID		INT,
	PER_FE_UMOD		DATETIME,
	ACC_DS_USR		VARCHAR(10)
)
GO

CREATE TABLE ACCESOS(
	ACC_PK_ID		INT PRIMARY KEY IDENTITY(1,1),
	ACC_DS_USR		VARCHAR(10),
	ACC_DS_PWDR		VARCHAR(50),
	ACC_FE_UACC		DATE,
	EDO_PK_ID		INT,
	ACC_FE_UMOD		DATETIME,
	ACC_DS_USRM		VARCHAR(10)
)
GO

CREATE TABLE RACCESSOSPERSONAS(
	RAP_PK_ID		INT PRIMARY KEY IDENTITY(1,1),
	ACC_PK_ID		INT,
	PNA_PK_ID		INT,
	EDO_PK_ID		INT,
	RAP_FE_UMOD		DATETIME,
	ACC_DS_USR		VARCHAR(10)
)
GO

-- 02 ESTRUCTURA DE ACCESOS Y ADMINISTRACION DEL SISTEMA
CREATE TABLE CPERSONAS(
	PNA_PK_ID			INT PRIMARY KEY IDENTITY(1,1),
	PNA_DS_NOMBRE		VARCHAR(150),
	PNA_DS_RFC			VARCHAR(25),
	PNA_PNL_JURIDICA	INT,
	PNA_FE_NACIMIENTO	DATE,
	PNA_FE_UMOD			DATETIME,
	ACC_DS_USR			VARCHAR(10)
)
GO

CREATE TABLE RPERSONASPERFILES(
	RPP_PK_ID		INT PRIMARY KEY IDENTITY(1,1),
	PER_PK_ID		INT,
	PNA_PK_ID		INT,
	EDO_PK_ID		INT,
	RPP_FE_UMOD		DATETIME,
	ACC_DS_USR		VARCHAR(10)
)
GO

CREATE TABLE RPERSONASROLES(
	RPP_PK_ID		INT PRIMARY KEY IDENTITY(1,1),
	ROL_PK_ID		INT,
	PNA_PK_ID		INT,
	EDO_PK_ID		INT,
	RPP_FE_UMOD		DATETIME,
	ACC_DS_USR		VARCHAR(10)
)
GO

CREATE TABLE CCORREOS(
	CRR_PK_ID		INT PRIMARY KEY IDENTITY(1,1),
	CRR_DS_CORREO	VARCHAR(150),
	CRR_REG_DEFAULT BIT,
	PNA_PK_ID		INT,
	EDO_PK_ID		INT,
	CRR_FE_UMOD		DATETIME,
	ACC_DS_USR		VARCHAr(10)
)
GO

CREATE TABLE CDIRECCIONES(
	DRN_PK_ID		INT PRIMARY KEY IDENTITY(1,1),
	DRN_DS_CPOST	VARCHAR(10),
	DRN_DS_CIUDAD	VARCHAR(50),
	DRN_DS_ESTADO	VARCHAR(50),
	DRN_DS_CALLE	VARCHAR(50),
	DRN_DS_NINT		VARCHAR(10),
	DRN_DS_NEXT		VARCHAR(10),
	DRN_REG_DEFAULT BIT,
	PNA_PK_ID		INT,
	EDO_PK_ID		INT,
	DRN_FE_UMOD		DATETIME,
	ACC_DS_USR		VARCHAr(10)
)
GO

CREATE TABLE CTELEFONOS(
	CTL_PK_ID		INT PRIMARY KEY IDENTITY(1,1),
	CTL_DS_TELEFONO	VARCHAR(10),
	CTL_REG_DEFAULT BIT,
	PNA_PK_ID		INT,
	EDO_PK_ID		INT,
	CTL_FE_UMOD		DATETIME,
	ACC_DS_USR		VARCHAr(10)
)
GO

CREATE TABLE RMENUSPERFILES(
	RMP_PK_ID		INT PRIMARY KEY IDENTITY(1,1),
	MEN_PK_ID		INT,
	PER_PK_ID		INT,
	EDO_PK_ID		INT,
	RMP_FE_UMOD		DATETIME,
	ACC_DS_USR		VARCHAR(10)
)
GO

CREATE TABLE CACCIONES(
	ACN_PK_ID			INT PRIMARY KEY IDENTITY(1,1),
	ACN_DS_DESCRIPCION	VARCHAR(50),
	EDO_PK_ID			INT,
	ACN_FE_UMOD			DATETIME,
	ACC_DS_USR			VARCHAR(10)
)
GO

CREATE TABLE RMENUSACCIONES(
	RMA_PK_ID		INT  PRIMARY KEY IDENTITY(1,1),
	MEN_PK_ID		INT,
	ACN_PK_ID		INT,
	RMA_DS_BOTON	VARCHAR(150),
	EDO_PK_ID		INT,
	RMA_FE_UMOD		DATETIME,
	ACC_DS_USR		VARCHAR(10)
)
GO

CREATE TABLE RACCIONESPERFILES(
	RAP_PK_ID		INT PRIMARY KEY IDENTITY(1,1),
	RMA_PK_ID		INT,
	PER_PK_ID		INT,
	EDO_PK_ID		INT,
	RAP_FE_UMOD		DATETIME,
	ACC_DS_USR		VARCHAR(10),
)
GO

-- INVENTARIOS
CREATE TABLE CUNIDADESMEDIDA(
	CUM_PK_ID			INT PRIMARY KEY IDENTITY(1,1),
	CUM_DS_DESCRIPCION	VARCHAR(50),
	CUM_DS_ABREVIADO	VARCHAR(5),
	EDO_PK_ID			INT,
	CUM_FE_UMOD			DATETIME,
	ACC_DS_USR			VARCHAR(10)
)
GO

CREATE TABLE CGRUPO(
	CGP_PK_ID INT PRIMARY KEY IDENTITY(1,1),
	CPG_DS_DESCRIPCION VARCHAR(100),
	EDO_PK_ID			INT,
	CGP_FE_UMOD			DATETIME,
	ACC_DS_USR			VARCHAR(10)
)
GO

CREATE TABLE CMARCA(
	CMC_PK_ID			INT PRIMARY KEY IDENTITY(1,1),
	CMC_DS_DESCRIPCION	VARCHAR(50),
	EDO_PK_ID			INT,
	CMC_FE_UMOD			DATETIME,
	ACC_DS_USR			VARCHAR(10)
)
GO

CREATE TABLE CPRODUCTO(
	CPD_PK_ID			INT PRIMARY KEY IDENTITY(1,1),
	CPD_DS_DESCRIPCION  VARCHAR(500),
	CUM_PK_ID			INT,
	CGP_PK_ID			INT,
	CMC_PK_ID			INT,
	EDO_PK_ID			INT,
	CPD_FE_UMOD			DATETIME,
	ACC_DS_USR			VARCHAR(10)
)
GO

CREATE TABLE HCOSTO(
	HCT_PK_ID			INT PRIMARY KEY IDENTITY(1,1),
	HCT_MTO_COSTO		DECIMAL(13,2),
	HCT_FE_INICIO		DATETIME,
	HCT_FE_FINAL		DATETIME,
	CPD_PK_ID			INT,
	EDO_PK_ID			INT,
	HCT_FE_UMOD			DATETIME,
	ACC_DS_USR			VARCHAR(10)
)
GO

CREATE TABLE HPRECIO(
	HPC_PK_ID			INT PRIMARY KEY IDENTITY(1,1),
	HPC_MTO_PRECIO		DECIMAL(13,2),
	HPC_FE_INICIO		DATETIME,
	HPC_FE_FINAL		DATETIME,
	CPD_PK_ID			INT,
	EDO_PK_ID			INT,
	CPD_FE_UMOD			DATETIME,
	ACC_DS_USR			VARCHAR(10)
)
GO

CREATE TABLE TEXISTENCIA(
	TEX_PK_ID			INT PRIMARY KEY IDENTITY(1,1),
	TEX_NO_UNIDADES		DECIMAL(13,2),
	TEX_STK_MIN			INT,
	TEX_STK_MAX			INT,
	HPC_PK_ID			INT,
	HCT_PK_ID			INT,
	CPD_PK_ID			INT,
	EDO_PK_ID			INT,
	CPD_FE_UMOD			DATETIME,
	ACC_DS_USR			VARCHAR(10)
)
GO

CREATE TABLE CTIPOENTRADAS(
	CTE_PK_ID			INT PRIMARY KEY IDENTITY(1,1),
	CTE_DS_DESCRIPCION	VARCHAR(50),
	EDO_PK_ID			INT,
	CPD_FE_UMOD			DATETIME,
	ACC_DS_USR			VARCHAR(10)
)
GO

CREATE TABLE TENTRADAS(
	TEA_PK_ID				INT PRIMARY KEY IDENTITY(1,1),
	TEA_NO_SUBTOTAL			DECIMAL(13,2),
	TEA_NO_IVA				DECIMAL(13,2),
	TEA_NO_TOTAL			DECIMAL(13,2),
	TEA_DS_OBSERVACIONES	VARCHAR(500),
	TEA_FE_ENTARDA			DATETIME,
	PNA_PK_ID				INT,
	CTE_PK_ID				INT,
	EDO_PK_ID				INT,
	CPD_FE_UMOD				DATETIME,
	ACC_DS_USR				VARCHAR(10)
)
GO

CREATE TABLE TENTRADASDETALLES(
	TED_PK_ID			INT PRIMARY KEY IDENTITY(1,1),
	TED_NO_CANTIDAD		DECIMAL(13,2),
	TED_NO_COSTO		DECIMAL(13,2),
	TED_NO_IVA			DECIMAL(13,2),
	TED_NO_SUBTOTAL		DECIMAL(13,2),
	TEA_PK_ID			INT,
	CPD_PK_ID			INT,
	EDO_PK_ID			INT,
	CPD_FE_UMOD			DATETIME,
	ACC_DS_USR			VARCHAR(10)
)
GO

CREATE TABLE CTIPOSALIDAS(
	CTS_PK_ID			INT PRIMARY KEY IDENTITY(1,1),
	CTS_DS_DESCRIPCION	VARCHAR(50),
	EDO_PK_ID			INT,
	CPD_FE_UMOD			DATETIME,
	ACC_DS_USR			VARCHAR(10)
)
GO

CREATE TABLE TSALIDAS(
	TSA_PK_ID				INT PRIMARY KEY IDENTITY(1,1),
	TSA_NO_SUBTOTAL			DECIMAL(13,2),
	TSA_NO_IVA				DECIMAL(13,2),
	TSA_NO_TOTAL			DECIMAL(13,2),
	TSA_DS_OBSERVACIONES	VARCHAR(500),
	TSA_FE_SALIDA			DATETIME,
	PNA_PK_ID				INT,
	CTS_PK_ID				INT,
	EDO_PK_ID				INT,
	CPD_FE_UMOD				DATETIME,
	ACC_DS_USR				VARCHAR(10)
)
GO

CREATE TABLE TSALIDASDETALLES(
	TSD_PK_ID			INT PRIMARY KEY IDENTITY(1,1),
	TSD_NO_CANTIDAD		DECIMAL(13,2),
	TSD_NO_COSTO		DECIMAL(13,2),
	TSD_NO_IVA			DECIMAL(13,2),
	TSD_NO_SUBTOTAL		DECIMAL(13,2),
	TSA_PK_ID			INT,
	CPD_PK_ID			INT,
	EDO_PK_ID			INT,
	CPD_FE_UMOD			DATETIME,
	ACC_DS_USR			VARCHAR(10)
)
GO