SELECT * FROM CESTADOS

--INSERT INTO CESTADOS  (EDO_DS_DESCRIPCION,
--						EDO_FE_UMOD,
--						ACC_DS_USR) VALUES
--('REGISTRADO',GETDATE(),'ROOT'),
--('ACTIVO',GETDATE(),'ROOT'),
--('INACTIVO',GETDATE(),'ROOT'),
--('SUSPENDIDO',GETDATE(),'ROOT'),
--('ELIMINADO',GETDATE(),'ROOT'),
--('BLOQUEADO',GETDATE(),'ROOT')

SELECT * FROM CACCIONES

--INSERT INTO CACCIONES  (ACN_DS_DESCRIPCION,
--						EDO_PK_ID,
--						ACN_FE_UMOD,
--						ACC_DS_USR) VALUES
--('CREAR',2,GETDATE(),'ROOT'),
--('CONSULTAR',2,GETDATE(),'ROOT'),
--('ACTUALIZAR',2,GETDATE(),'ROOT'),
--('ELIMINAR',2,GETDATE(),'ROOT'),
--('IMPRIMIR',2,GETDATE(),'ROOT'),
--('AUTORIZAR',2,GETDATE(),'ROOT')

SELECT * FROM CROLES

--INSERT INTO CROLES (ROL_DS_DESCRIPCION, 
--					EDO_PK_ID, 
--					ROL_FE_UMOD,
--					ACC_DS_USR) VALUES
--('USUARIO',2,GETDATE(),'ROOT'),
--('CLIENTE',2,GETDATE(),'ROOT'),
--('PROVEEDOR',2,GETDATE(),'ROOT')

SELECT * FROM CPERFILES

--INSERT INTO CPERFILES  (PER_DS_PERFIL,
--						EDO_PK_ID,
--						PER_FE_UMOD,
--						ACC_DS_USR) VALUES
--('ADMINISTRADOR',2,GETDATE(),'ROOT'),
--('SUPERVISOR',2,GETDATE(),'ROOT'),
--('VENDEDOR',2,GETDATE(),'ROOT')

SELECT * FROM ACCESOS

--INSERT INTO ACCESOS	   (ACC_DS_USR,
--						ACC_DS_PWDR,
--						ACC_FE_UACC,
--						EDO_PK_ID,
--						ACC_FE_UMOD,
--						ACC_DS_USRM) VALUES
--('ADMIN','95753',GETDATE(),2,GETDATE(),'ROOT')

SELECT * FROM CPERSONAS

--INSERT INTO CPERSONAS  (PNA_DS_NOMBRE,
--						PNA_DS_RFC,
--						PNA_PNL_JURIDICA,
--						PNA_FE_NACIMIENTO,
--						PNA_FE_UMOD,
--						ACC_DS_USR) VALUES
--('ADMINISTRADOR DE SISTEMAS','ADMN000000111',1,GETDATE(),GETDATE(),'ROOT')

SELECT * FROM RPERSONASROLES

--INSERT INTO RPERSONASROLES (ROL_PK_ID,
--							PNA_PK_ID,
--							EDO_PK_ID,
--							RPP_FE_UMOD,
--							ACC_DS_USR) VALUES
--(1,1,2,GETDATE(),'ROOT')

SELECT * FROM RACCESSOSPERSONAS

--INSERT INTO RACCESSOSPERSONAS  (ACC_PK_ID,
--								PNA_PK_ID,
--								EDO_PK_ID,
--								RAP_FE_UMOD,
--								ACC_DS_USR) VALUES
--(1,1,2,GETDATE(),'ROOT')

SELECT * FROM RPERSONASPERFILES

--INSERT INTO RPERSONASPERFILES  (PER_PK_ID,
--								PNA_PK_ID,
--								EDO_PK_ID,
--								RPP_FE_UMOD,
--								ACC_DS_USR) VALUES
--(1,1,2,GETDATE(),'ROOT')

SELECT * FROM CMENUS

--INSERT INTO CMENUS (MEN_NO_NIVEL,
--					MEN_ID_PADRE,
--					MEN_DS_MENU,
--					MEN_DS_ICONO,
--					MEN_DS_RUTA,
--					EDO_PK_ID,
--					MEN_FE_UMOD,
--					ACC_DS_USR) VALUES
--(1,0,'Ventas','','',2,GETDATE(),'ROOT'),
--(1,0,'Inventarios','','',2,GETDATE(),'ROOT'),
--(1,0,'Catalogos','','',2,GETDATE(),'ROOT'),
--(1,0,'Reportes','','',2,GETDATE(),'ROOT'),
--(1,0,'Administracion','','',2,GETDATE(),'ROOT')

SELECT * FROM RMENUSPERFILES

--INSERT INTO RMENUSPERFILES (MEN_PK_ID,
--							PER_PK_ID,
--							EDO_PK_ID,
--							RMP_FE_UMOD,
--							ACC_DS_USR) VALUES
--(1,1,2,GETDATE(),'ROOT'),
--(2,1,2,GETDATE(),'ROOT'),
--(3,1,2,GETDATE(),'ROOT'),
--(4,1,2,GETDATE(),'ROOT'),
--(5,1,2,GETDATE(),'ROOT')
